// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgC6jiUo6bJtgzBPosNpjvXV9LZ0Eip90',
    appId: '1:30582023239:web:eec819f8c26f26cb3efd62',
    messagingSenderId: '30582023239',
    projectId: 'accountapp-ca686',
    authDomain: 'accountapp-ca686.firebaseapp.com',
    storageBucket: 'accountapp-ca686.firebasestorage.app',
    measurementId: 'G-3Z96GX93P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIc4PNqg0AB9UfAVdce-zKbLeFv600pcU',
    appId: '1:30582023239:android:429ff1995f146d603efd62',
    messagingSenderId: '30582023239',
    projectId: 'accountapp-ca686',
    storageBucket: 'accountapp-ca686.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZYofwPDeaLgl0j_aLhT6cI-RtJx96zw',
    appId: '1:30582023239:ios:f318479ef5965aea3efd62',
    messagingSenderId: '30582023239',
    projectId: 'accountapp-ca686',
    storageBucket: 'accountapp-ca686.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbZYofwPDeaLgl0j_aLhT6cI-RtJx96zw',
    appId: '1:30582023239:ios:f318479ef5965aea3efd62',
    messagingSenderId: '30582023239',
    projectId: 'accountapp-ca686',
    storageBucket: 'accountapp-ca686.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgC6jiUo6bJtgzBPosNpjvXV9LZ0Eip90',
    appId: '1:30582023239:web:1cef5e14b01f98523efd62',
    messagingSenderId: '30582023239',
    projectId: 'accountapp-ca686',
    authDomain: 'accountapp-ca686.firebaseapp.com',
    storageBucket: 'accountapp-ca686.firebasestorage.app',
    measurementId: 'G-MXCTCL6D3G',
  );
}
